# 🛠️ Build Stage
FROM gradle:8.5-jdk17 AS builder
WORKDIR /app

COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN gradle war

# 🚀 Runtime Stage with Tomcat
FROM tomcat:10.1-jdk17
ARG PORT
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_PROFILES_ACTIVE
ARG RAILWAY_SERVICE_PROCONNECTX_UI_URL

ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
    SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
    SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
    SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
    ALLOWED_ORIGINS=$RAILWAY_SERVICE_PROCONNECTX_UI_URL

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=builder /app/build/libs/*.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080