export enum BidStatus {
    NEW = "NEW",
    IN_REVIEW = "IN_REVIEW",
    APPROVED = "APPROVED",
    DECLINED = "DECLINED"
}

export enum ERole {
    ROLE_CLIENT = "ROLE_CLIENT",
    ROLE_FREELANCER = "ROLE_FREELANCER",
    ROLE_ADMIN = "ROLE_ADMIN"
}

export enum Category {
    WEB_DESIGN = "WEB_DESIGN",
    WEB_DEVELOPMENT = "WEB_DEVELOPMENT",
    MOBILE_DEVELOPMENT = "MOBILE_DEVELOPMENT",
    GRAPHIC_DESIGN = "GRAPHIC_DESIGN",
    VIDEO_EDITING = "VIDEO_EDITING",
    WRITING = "WRITING",
    TRANSLATION = "TRANSLATION",
    MARKETING = "MARKETING",
    SALES = "SALES",
    CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
    ADMIN_SUPPORT = "ADMIN_SUPPORT",
    DATA_SCIENCE = "DATA_SCIENCE",
    ENGINEERING = "ENGINEERING",
    ACCOUNTING = "ACCOUNTING",
    LEGAL = "LEGAL",
    OTHER = "OTHER"
}

export enum ProjectStatus {
    OPEN = "OPEN",
    IN_PROGRESS = "IN_PROGRESS",
    CLOSED = "CLOSED"
}

