package com.nick1est.proconnectx.dao;

public enum AppEventType {
    // Onboarding
    PROFILE_INITIATED,
    VERIFICATION_SUBMITTED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,

    // Order lifecycle
    ORDER_PLACED,
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    WORK_SUBMITTED_FOR_REVIEW,
    ORDER_APPROVED_BY_CLIENT,
    ORDER_DISPUTED_BY_CLIENT,
    ORDER_COMPLETED,
    REVIEW_SUBMITTED,

    PROFILE_CREATED, // Admin alerts
    PROFILE_VERIFIED, PROFILE_REJECTED, NEW_USER_AWAITING_VERIFICATION
}
