package com.nick1est.proconnectx.dao;

public enum AppEventType {
    // Onboarding
    PROFILE_INITIATED,
    VERIFICATION_SUBMITTED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,

    // Order lifecycle
    ORDER_PLACED,
    ORDER_ACCEPTED,
    ORDER_CANCELED,
    ORDER_CANCELED_BY_ADMIN,
    ORDER_SUBMITTED_FOR_REVIEW,
    ORDER_APPROVED,
    ORDER_APPROVED_BY_ADMIN,
    ORDER_DISPUTED,
    ORDER_COMPLETED,
    REVIEW_SUBMITTED,

    // Dispute lifecycle
    DISPUTE_CREATED,
    DISPUTE_RESOLVED,
    DISPUTE_REJECTED,
    PROPOSAL_CREATED,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    ADMIN_NOTIFY,

    PROFILE_CREATED, // Admin alerts
    PROFILE_VERIFIED, PROFILE_REJECTED, PROPOSAL_ACCEPTED_BY_ADMIN, PROPOSAL_REJECTED_BY_ADMIN, NEW_USER_AWAITING_VERIFICATION
}
