package com.nick1est.proconnectx.dao;

public enum Field {
    WEB_DESIGN,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    GRAPHIC_DESIGN,
    VIDEO_EDITING,
    WRITING,
    TRANSLATION,
    MARKETING,
    SALES,
    CUSTOMER_SERVICE,
    ADMIN_SUPPORT,
    DATA_SCIENCE,
    ENGINEERING,
    ACCOUNTING,
    LEGAL,
    OTHER
}
