// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClientMainInfo,
    ClientMainInfoFromJSON,
    ClientMainInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface BidCardDto
 */
export interface BidCardDto  {
    /**
     * 
     * @type {number}
     * @memberof BidCardDto
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof BidCardDto
     */
    amount: number;
    /**
     * 
     * @type {ClientMainInfo}
     * @memberof BidCardDto
     */
    owner: ClientMainInfo;
    /**
     * 
     * @type {string}
     * @memberof BidCardDto
     */
    coverLetter?: string;
    /**
     * 
     * @type {string}
     * @memberof BidCardDto
     */
    shortCoverLetter?: string;
    /**
     * 
     * @type {string}
     * @memberof BidCardDto
     */
    status: BidCardDtoStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof BidCardDto
     */
    dueDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BidCardDto
     */
    datePosted: Date;
}

export function BidCardDtoFromJSON(json: any): BidCardDto {
    return {
        'id': json['id'],
        'amount': json['amount'],
        'owner': ClientMainInfoFromJSON(json['owner']),
        'coverLetter': !exists(json, 'coverLetter') ? undefined : json['coverLetter'],
        'shortCoverLetter': !exists(json, 'shortCoverLetter') ? undefined : json['shortCoverLetter'],
        'status': json['status'],
        'dueDate': !exists(json, 'dueDate') ? undefined : new Date(json['dueDate']),
        'datePosted': new Date(json['datePosted']),
    };
}

export function BidCardDtoToJSON(value?: BidCardDto): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'amount': value.amount,
        'owner': ClientMainInfoToJSON(value.owner),
        'coverLetter': value.coverLetter,
        'shortCoverLetter': value.shortCoverLetter,
        'status': value.status,
        'dueDate': value.dueDate === undefined ? undefined : value.dueDate.toISOString().substr(0,10),
        'datePosted': value.datePosted.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum BidCardDtoStatusEnum {
    New = 'NEW',
    InReview = 'IN_REVIEW',
    Approved = 'APPROVED',
    Declined = 'DECLINED'
}


