// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BidRequest
 */
export interface BidRequest  {
    /**
     * 
     * @type {number}
     * @memberof BidRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof BidRequest
     */
    coverLetter?: string;
    /**
     * 
     * @type {string}
     * @memberof BidRequest
     */
    shortCoverLetter?: string;
    /**
     * 
     * @type {Date}
     * @memberof BidRequest
     */
    dueDate?: Date;
}

export function BidRequestFromJSON(json: any): BidRequest {
    return {
        'amount': json['amount'],
        'coverLetter': !exists(json, 'coverLetter') ? undefined : json['coverLetter'],
        'shortCoverLetter': !exists(json, 'shortCoverLetter') ? undefined : json['shortCoverLetter'],
        'dueDate': !exists(json, 'dueDate') ? undefined : new Date(json['dueDate']),
    };
}

export function BidRequestToJSON(value?: BidRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'amount': value.amount,
        'coverLetter': value.coverLetter,
        'shortCoverLetter': value.shortCoverLetter,
        'dueDate': value.dueDate === undefined ? undefined : value.dueDate.toISOString().substr(0,10),
    };
}


