// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientMainInfo
 */
export interface ClientMainInfo  {
    /**
     * 
     * @type {number}
     * @memberof ClientMainInfo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientMainInfo
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientMainInfo
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientMainInfo
     */
    profilePicture?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientMainInfo
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientMainInfo
     */
    ratingCount?: number;
}

export function ClientMainInfoFromJSON(json: any): ClientMainInfo {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'profilePicture': !exists(json, 'profilePicture') ? undefined : json['profilePicture'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'ratingCount': !exists(json, 'ratingCount') ? undefined : json['ratingCount'],
    };
}

export function ClientMainInfoToJSON(value?: ClientMainInfo): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'profilePicture': value.profilePicture,
        'rating': value.rating,
        'ratingCount': value.ratingCount,
    };
}


