// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Principal,
    PrincipalFromJSON,
    PrincipalToJSON,
} from './';

/**
 * 
 * @export
 * @interface Employer
 */
export interface Employer  {
    /**
     * 
     * @type {number}
     * @memberof Employer
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Employer
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Employer
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Employer
     */
    profilePicture?: string;
    /**
     * 
     * @type {string}
     * @memberof Employer
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof Employer
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof Employer
     */
    ratingCount?: number;
    /**
     * 
     * @type {Principal}
     * @memberof Employer
     */
    principal: Principal;
}

export function EmployerFromJSON(json: any): Employer {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'profilePicture': !exists(json, 'profilePicture') ? undefined : json['profilePicture'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'ratingCount': !exists(json, 'ratingCount') ? undefined : json['ratingCount'],
        'principal': PrincipalFromJSON(json['principal']),
    };
}

export function EmployerToJSON(value?: Employer): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'profilePicture': value.profilePicture,
        'location': value.location,
        'rating': value.rating,
        'ratingCount': value.ratingCount,
        'principal': PrincipalToJSON(value.principal),
    };
}


