// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorMessage
 */
export interface ErrorMessage  {
    /**
     * 
     * @type {string}
     * @memberof ErrorMessage
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorMessage
     */
    message?: string;
}

export function ErrorMessageFromJSON(json: any): ErrorMessage {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorMessageToJSON(value?: ErrorMessage): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'message': value.message,
    };
}


