// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FormResponse
 */
export interface FormResponse  {
    /**
     * 
     * @type {string}
     * @memberof FormResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FormResponse
     */
    success?: boolean;
}

export function FormResponseFromJSON(json: any): FormResponse {
    return {
        'message': !exists(json, 'message') ? undefined : json['message'],
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function FormResponseToJSON(value?: FormResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'message': value.message,
        'success': value.success,
    };
}


