// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FreelancerFilterResponse
 */
export interface FreelancerFilterResponse  {
    /**
     * 
     * @type {number}
     * @memberof FreelancerFilterResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FreelancerFilterResponse
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof FreelancerFilterResponse
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof FreelancerFilterResponse
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FreelancerFilterResponse
     */
    categories?: Array<FreelancerFilterResponseCategoriesEnum>;
    /**
     * 
     * @type {string}
     * @memberof FreelancerFilterResponse
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof FreelancerFilterResponse
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof FreelancerFilterResponse
     */
    ratingCount?: number;
}

export function FreelancerFilterResponseFromJSON(json: any): FreelancerFilterResponse {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'ratingCount': !exists(json, 'ratingCount') ? undefined : json['ratingCount'],
    };
}

export function FreelancerFilterResponseToJSON(value?: FreelancerFilterResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'description': value.description,
        'categories': value.categories,
        'location': value.location,
        'rating': value.rating,
        'ratingCount': value.ratingCount,
    };
}

/**
* @export
* @enum {string}
*/
export enum FreelancerFilterResponseCategoriesEnum {
    WebDesign = 'WEB_DESIGN',
    WebDevelopment = 'WEB_DEVELOPMENT',
    MobileDevelopment = 'MOBILE_DEVELOPMENT',
    GraphicDesign = 'GRAPHIC_DESIGN',
    VideoEditing = 'VIDEO_EDITING',
    Writing = 'WRITING',
    Translation = 'TRANSLATION',
    Marketing = 'MARKETING',
    Sales = 'SALES',
    CustomerService = 'CUSTOMER_SERVICE',
    AdminSupport = 'ADMIN_SUPPORT',
    DataScience = 'DATA_SCIENCE',
    Engineering = 'ENGINEERING',
    Accounting = 'ACCOUNTING',
    Legal = 'LEGAL',
    Other = 'OTHER'
}


