// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageResponse
 */
export interface MessageResponse  {
    /**
     * 
     * @type {string}
     * @memberof MessageResponse
     */
    message?: string;
}

export function MessageResponseFromJSON(json: any): MessageResponse {
    return {
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function MessageResponseToJSON(value?: MessageResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'message': value.message,
    };
}


