// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Role,
    RoleFromJSON,
    RoleToJSON,
} from './';

/**
 * 
 * @export
 * @interface Principal
 */
export interface Principal  {
    /**
     * 
     * @type {number}
     * @memberof Principal
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Principal
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Principal
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Principal
     */
    lastName: string;
    /**
     * 
     * @type {Set<Role>}
     * @memberof Principal
     */
    roles?: Set<Role>;
}

export function PrincipalFromJSON(json: any): Principal {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'roles': !exists(json, 'roles') ? undefined : (json['roles'] as Array<any>).map(RoleFromJSON),
    };
}

export function PrincipalToJSON(value?: Principal): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'roles': value.roles === undefined ? undefined : (value.roles as Array<any>).map(RoleToJSON),
    };
}


