// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectCreateDto
 */
export interface ProjectCreateDto  {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    shortDescription: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreateDto
     */
    categories: Array<ProjectCreateDtoCategoriesEnum>;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    projectType: ProjectCreateDtoProjectTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateDto
     */
    budget?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateDto
     */
    minSatisfyingBid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateDto
     */
    bidStep?: number;
}

export function ProjectCreateDtoFromJSON(json: any): ProjectCreateDto {
    return {
        'title': json['title'],
        'description': json['description'],
        'shortDescription': json['shortDescription'],
        'categories': json['categories'],
        'location': json['location'],
        'projectType': json['projectType'],
        'budget': !exists(json, 'budget') ? undefined : json['budget'],
        'minSatisfyingBid': !exists(json, 'minSatisfyingBid') ? undefined : json['minSatisfyingBid'],
        'bidStep': !exists(json, 'bidStep') ? undefined : json['bidStep'],
    };
}

export function ProjectCreateDtoToJSON(value?: ProjectCreateDto): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'title': value.title,
        'description': value.description,
        'shortDescription': value.shortDescription,
        'categories': value.categories,
        'location': value.location,
        'projectType': value.projectType,
        'budget': value.budget,
        'minSatisfyingBid': value.minSatisfyingBid,
        'bidStep': value.bidStep,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProjectCreateDtoCategoriesEnum {
    WebDesign = 'WEB_DESIGN',
    WebDevelopment = 'WEB_DEVELOPMENT',
    MobileDevelopment = 'MOBILE_DEVELOPMENT',
    GraphicDesign = 'GRAPHIC_DESIGN',
    VideoEditing = 'VIDEO_EDITING',
    Writing = 'WRITING',
    Translation = 'TRANSLATION',
    Marketing = 'MARKETING',
    Sales = 'SALES',
    CustomerService = 'CUSTOMER_SERVICE',
    AdminSupport = 'ADMIN_SUPPORT',
    DataScience = 'DATA_SCIENCE',
    Engineering = 'ENGINEERING',
    Accounting = 'ACCOUNTING',
    Legal = 'LEGAL',
    Other = 'OTHER'
}
/**
* @export
* @enum {string}
*/
export enum ProjectCreateDtoProjectTypeEnum {
    Bid = 'BID',
    Fixed = 'FIXED'
}


