// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectFilter
 */
export interface ProjectFilter  {
    /**
     * 
     * @type {string}
     * @memberof ProjectFilter
     */
    title?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectFilter
     */
    categories?: Array<ProjectFilterCategoriesEnum>;
    /**
     * 
     * @type {string}
     * @memberof ProjectFilter
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectFilter
     */
    minBudget?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectFilter
     */
    maxBudget?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectFilter
     */
    type?: ProjectFilterTypeEnum;
}

export function ProjectFilterFromJSON(json: any): ProjectFilter {
    return {
        'title': !exists(json, 'title') ? undefined : json['title'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'minBudget': !exists(json, 'minBudget') ? undefined : json['minBudget'],
        'maxBudget': !exists(json, 'maxBudget') ? undefined : json['maxBudget'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ProjectFilterToJSON(value?: ProjectFilter): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'title': value.title,
        'categories': value.categories,
        'location': value.location,
        'minBudget': value.minBudget,
        'maxBudget': value.maxBudget,
        'type': value.type,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProjectFilterCategoriesEnum {
    WebDesign = 'WEB_DESIGN',
    WebDevelopment = 'WEB_DEVELOPMENT',
    MobileDevelopment = 'MOBILE_DEVELOPMENT',
    GraphicDesign = 'GRAPHIC_DESIGN',
    VideoEditing = 'VIDEO_EDITING',
    Writing = 'WRITING',
    Translation = 'TRANSLATION',
    Marketing = 'MARKETING',
    Sales = 'SALES',
    CustomerService = 'CUSTOMER_SERVICE',
    AdminSupport = 'ADMIN_SUPPORT',
    DataScience = 'DATA_SCIENCE',
    Engineering = 'ENGINEERING',
    Accounting = 'ACCOUNTING',
    Legal = 'LEGAL',
    Other = 'OTHER'
}
/**
* @export
* @enum {string}
*/
export enum ProjectFilterTypeEnum {
    Bid = 'BID',
    Fixed = 'FIXED'
}


