// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClientMainInfo,
    ClientMainInfoFromJSON,
    ClientMainInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProjectPublicDto
 */
export interface ProjectPublicDto  {
    /**
     * 
     * @type {number}
     * @memberof ProjectPublicDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectPublicDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectPublicDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectPublicDto
     */
    shortDescription?: string;
    /**
     * 
     * @type {ClientMainInfo}
     * @memberof ProjectPublicDto
     */
    owner: ClientMainInfo;
    /**
     * 
     * @type {number}
     * @memberof ProjectPublicDto
     */
    budget?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectPublicDto
     */
    categories: Array<ProjectPublicDtoCategoriesEnum>;
    /**
     * 
     * @type {string}
     * @memberof ProjectPublicDto
     */
    status: ProjectPublicDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ProjectPublicDto
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectPublicDto
     */
    projectType: ProjectPublicDtoProjectTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ProjectPublicDto
     */
    bidCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectPublicDto
     */
    maxBid?: number;
    /**
     * 
     * @type {Date}
     * @memberof ProjectPublicDto
     */
    dueDate?: Date;
}

export function ProjectPublicDtoFromJSON(json: any): ProjectPublicDto {
    return {
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'shortDescription': !exists(json, 'shortDescription') ? undefined : json['shortDescription'],
        'owner': ClientMainInfoFromJSON(json['owner']),
        'budget': !exists(json, 'budget') ? undefined : json['budget'],
        'categories': json['categories'],
        'status': json['status'],
        'location': json['location'],
        'projectType': json['projectType'],
        'bidCount': !exists(json, 'bidCount') ? undefined : json['bidCount'],
        'maxBid': !exists(json, 'maxBid') ? undefined : json['maxBid'],
        'dueDate': !exists(json, 'dueDate') ? undefined : new Date(json['dueDate']),
    };
}

export function ProjectPublicDtoToJSON(value?: ProjectPublicDto): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'shortDescription': value.shortDescription,
        'owner': ClientMainInfoToJSON(value.owner),
        'budget': value.budget,
        'categories': value.categories,
        'status': value.status,
        'location': value.location,
        'projectType': value.projectType,
        'bidCount': value.bidCount,
        'maxBid': value.maxBid,
        'dueDate': value.dueDate === undefined ? undefined : value.dueDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum ProjectPublicDtoCategoriesEnum {
    WebDesign = 'WEB_DESIGN',
    WebDevelopment = 'WEB_DEVELOPMENT',
    MobileDevelopment = 'MOBILE_DEVELOPMENT',
    GraphicDesign = 'GRAPHIC_DESIGN',
    VideoEditing = 'VIDEO_EDITING',
    Writing = 'WRITING',
    Translation = 'TRANSLATION',
    Marketing = 'MARKETING',
    Sales = 'SALES',
    CustomerService = 'CUSTOMER_SERVICE',
    AdminSupport = 'ADMIN_SUPPORT',
    DataScience = 'DATA_SCIENCE',
    Engineering = 'ENGINEERING',
    Accounting = 'ACCOUNTING',
    Legal = 'LEGAL',
    Other = 'OTHER'
}
/**
* @export
* @enum {string}
*/
export enum ProjectPublicDtoStatusEnum {
    Open = 'OPEN',
    InProgress = 'IN_PROGRESS',
    Closed = 'CLOSED'
}
/**
* @export
* @enum {string}
*/
export enum ProjectPublicDtoProjectTypeEnum {
    Bid = 'BID',
    Fixed = 'FIXED'
}


