// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClientMainInfo,
    ClientMainInfoFromJSON,
    ClientMainInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ServiceFilterResponse
 */
export interface ServiceFilterResponse  {
    /**
     * 
     * @type {number}
     * @memberof ServiceFilterResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceFilterResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceFilterResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceFilterResponse
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceFilterResponse
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceFilterResponse
     */
    ratingCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceFilterResponse
     */
    price?: number;
    /**
     * 
     * @type {ClientMainInfo}
     * @memberof ServiceFilterResponse
     */
    owner?: ClientMainInfo;
    /**
     * 
     * @type {string}
     * @memberof ServiceFilterResponse
     */
    category?: ServiceFilterResponseCategoryEnum;
}

export function ServiceFilterResponseFromJSON(json: any): ServiceFilterResponse {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'ratingCount': !exists(json, 'ratingCount') ? undefined : json['ratingCount'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'owner': !exists(json, 'owner') ? undefined : ClientMainInfoFromJSON(json['owner']),
        'category': !exists(json, 'category') ? undefined : json['category'],
    };
}

export function ServiceFilterResponseToJSON(value?: ServiceFilterResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'location': value.location,
        'rating': value.rating,
        'ratingCount': value.ratingCount,
        'price': value.price,
        'owner': ClientMainInfoToJSON(value.owner),
        'category': value.category,
    };
}

/**
* @export
* @enum {string}
*/
export enum ServiceFilterResponseCategoryEnum {
    WebDesign = 'WEB_DESIGN',
    WebDevelopment = 'WEB_DEVELOPMENT',
    MobileDevelopment = 'MOBILE_DEVELOPMENT',
    GraphicDesign = 'GRAPHIC_DESIGN',
    VideoEditing = 'VIDEO_EDITING',
    Writing = 'WRITING',
    Translation = 'TRANSLATION',
    Marketing = 'MARKETING',
    Sales = 'SALES',
    CustomerService = 'CUSTOMER_SERVICE',
    AdminSupport = 'ADMIN_SUPPORT',
    DataScience = 'DATA_SCIENCE',
    Engineering = 'ENGINEERING',
    Accounting = 'ACCOUNTING',
    Legal = 'LEGAL',
    Other = 'OTHER'
}


