// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceFilter
 */
export interface ServiceFilter  {
    /**
     * 
     * @type {string}
     * @memberof ServiceFilter
     */
    title?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ServiceFilter
     */
    categories?: Array<ServiceFilterCategoriesEnum>;
    /**
     * 
     * @type {string}
     * @memberof ServiceFilter
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceFilter
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceFilter
     */
    minBudget?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceFilter
     */
    maxBudget?: number;
}

export function ServiceFilterFromJSON(json: any): ServiceFilter {
    return {
        'title': !exists(json, 'title') ? undefined : json['title'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'minBudget': !exists(json, 'minBudget') ? undefined : json['minBudget'],
        'maxBudget': !exists(json, 'maxBudget') ? undefined : json['maxBudget'],
    };
}

export function ServiceFilterToJSON(value?: ServiceFilter): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'title': value.title,
        'categories': value.categories,
        'location': value.location,
        'rating': value.rating,
        'minBudget': value.minBudget,
        'maxBudget': value.maxBudget,
    };
}

/**
* @export
* @enum {string}
*/
export enum ServiceFilterCategoriesEnum {
    WebDesign = 'WEB_DESIGN',
    WebDevelopment = 'WEB_DEVELOPMENT',
    MobileDevelopment = 'MOBILE_DEVELOPMENT',
    GraphicDesign = 'GRAPHIC_DESIGN',
    VideoEditing = 'VIDEO_EDITING',
    Writing = 'WRITING',
    Translation = 'TRANSLATION',
    Marketing = 'MARKETING',
    Sales = 'SALES',
    CustomerService = 'CUSTOMER_SERVICE',
    AdminSupport = 'ADMIN_SUPPORT',
    DataScience = 'DATA_SCIENCE',
    Engineering = 'ENGINEERING',
    Accounting = 'ACCOUNTING',
    Legal = 'LEGAL',
    Other = 'OTHER'
}


