// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceCreateDto
 */
export interface ServiceCreateDto  {
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateDto
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceCreateDto
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateDto
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateDto
     */
    category: ServiceCreateDtoCategoryEnum;
}

export function ServiceCreateDtoFromJSON(json: any): ServiceCreateDto {
    return {
        'title': json['title'],
        'description': json['description'],
        'price': json['price'],
        'location': json['location'],
        'category': json['category'],
    };
}

export function ServiceCreateDtoToJSON(value?: ServiceCreateDto): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'title': value.title,
        'description': value.description,
        'price': value.price,
        'location': value.location,
        'category': value.category,
    };
}

/**
* @export
* @enum {string}
*/
export enum ServiceCreateDtoCategoryEnum {
    WebDesign = 'WEB_DESIGN',
    WebDevelopment = 'WEB_DEVELOPMENT',
    MobileDevelopment = 'MOBILE_DEVELOPMENT',
    GraphicDesign = 'GRAPHIC_DESIGN',
    VideoEditing = 'VIDEO_EDITING',
    Writing = 'WRITING',
    Translation = 'TRANSLATION',
    Marketing = 'MARKETING',
    Sales = 'SALES',
    CustomerService = 'CUSTOMER_SERVICE',
    AdminSupport = 'ADMIN_SUPPORT',
    DataScience = 'DATA_SCIENCE',
    Engineering = 'ENGINEERING',
    Accounting = 'ACCOUNTING',
    Legal = 'LEGAL',
    Other = 'OTHER'
}


