// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Category,
    CategoryFromJSON,
    CategoryToJSON,
} from './';

/**
 * 
 * @export
 * @interface ServiceDao
 */
export interface ServiceDao  {
    /**
     * 
     * @type {number}
     * @memberof ServiceDao
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceDao
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDao
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceDao
     */
    price?: number;
    /**
     * 
     * @type {object}
     * @memberof ServiceDao
     */
    freelancer?: object;
    /**
     * 
     * @type {Array<object>}
     * @memberof ServiceDao
     */
    comments?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof ServiceDao
     */
    location?: string;
    /**
     * 
     * @type {Category}
     * @memberof ServiceDao
     */
    category?: Category;
    /**
     * 
     * @type {number}
     * @memberof ServiceDao
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceDao
     */
    ratingCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof ServiceDao
     */
    datePosted?: Date;
}

export function ServiceDaoFromJSON(json: any): ServiceDao {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'freelancer': !exists(json, 'freelancer') ? undefined : json['freelancer'],
        'comments': !exists(json, 'comments') ? undefined : json['comments'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'category': !exists(json, 'category') ? undefined : CategoryFromJSON(json['category']),
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'ratingCount': !exists(json, 'ratingCount') ? undefined : json['ratingCount'],
        'datePosted': !exists(json, 'datePosted') ? undefined : new Date(json['datePosted']),
    };
}

export function ServiceDaoToJSON(value?: ServiceDao): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'price': value.price,
        'freelancer': value.freelancer,
        'comments': value.comments,
        'location': value.location,
        'category': CategoryToJSON(value.category),
        'rating': value.rating,
        'ratingCount': value.ratingCount,
        'datePosted': value.datePosted === undefined ? undefined : value.datePosted.toISOString(),
    };
}


