// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest  {
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    password: string;
}

export function SignupRequestFromJSON(json: any): SignupRequest {
    return {
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignupRequestToJSON(value?: SignupRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'password': value.password,
    };
}


