// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDetailsResponse
 */
export interface UserDetailsResponse  {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDetailsResponse
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsResponse
     */
    activeRole?: string;
}

export function UserDetailsResponseFromJSON(json: any): UserDetailsResponse {
    return {
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
        'activeRole': !exists(json, 'activeRole') ? undefined : json['activeRole'],
    };
}

export function UserDetailsResponseToJSON(value?: UserDetailsResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'roles': value.roles,
        'activeRole': value.activeRole,
    };
}


